FROM golang:1.15

ENV APP_HOME /go/src/app
COPY . $APP_HOME
WORKDIR $APP_HOME

RUN go get -d -v ./...
RUN go build

ARG CLOUD66_RELEASE_VERSION
ARG CLOUD66_RELEASE_CREATED_AT

RUN echo $CLOUD66_RELEASE_VERSION > /tmp/CLOUD66_RELEASE_VERSION
RUN echo $CLOUD66_RELEASE_CREATED_AT > /tmp/CLOUD66_RELEASE_CREATED_AT
